# Generated by Django 4.2 on 2025-05-13 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_create_logs_dir'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='active_requests',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='rejected_today',
        ),
        migrations.RemoveField(
            model_name='request',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='request',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='request',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='manager',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='status',
            field=models.CharField(choices=[('free', 'Свободен'), ('busy', 'В работе'), ('day_off', 'Выходной')], default='free', max_length=20),
        ),
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.city'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.manager'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Не назначена'), ('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Исполнена'), ('rejected', 'Отказ')], default='unassigned', max_length=20),
        ),
    ]
